propel:
  _attributes:      { package: plugins.sfPropelOAuthPlugin.lib.model }
  
  token:
    _attributes:    { phpName: Token }
    id:             ~
    name:           { type: varchar, size: 255 }
    token_key:      { type: varchar, index: true }
    token_secret:   { type: varchar }
    user_id:        { type: integer, primaryKey: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    expire:         { type: integer }
    params:         { type: varchar }
    identifier:     { type: varchar, size: 255 }
    status:         { type: varchar, size: 255 }
    o_auth_version: { type: integer }
    created_at:     ~
    updated_at:     ~
    _uniques:
      token_key: [token_key]